### PR TITLE
Support new project and data folder structure.

### PR DESCRIPTION
**Pull request by sbc**
This PR fixes issues caused by changes to the project and data folder structure. It also updates the base Docker image because I was getting numpy import errors with the old base image. NOTE: The pipeline is "running" now, but I'm still getting the following error:

` 'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings. Visit https://speechbrain.github.io for installation instructions.`

I tried adding it to the requirements.txt file without success.

### CODE REVIEW

**Comment by sbc** [comment]
Found this related issue: https://github.com/pyannote/pyannote-audio/issues/1661

**Comment by sbc** [comment]
Tried pegging `pyannote-audio==3.0.1` in requirements.txt resulting in build errors:

> INFO: pip is looking at multiple versions of pyannote-audio to determine which version is compatible with other requirements. This could take a while.
> 109.9 ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.16.0 (from pyannote-audio) (from versions: none)
> 109.9 ERROR: No matching distribution found for onnxruntime-gpu>=1.16.0

Any ideas @mochan-a ?

**Comment by cataluna84** [comment]
I can run this STT installation setup after this PR is merged, which supports the new project structure. 

Between @sbc, you should remain on `pyannote-audio==3.1.1` as  you can install `speechbrain` via `pip install git+https://github.com/speechbrain/speechbrain.git@develop` command. See, SpeechBrain's ECAPA-TDNN embeddings on Voxceleb via [HuggingFace](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb) for details.

**Comment by mochan-a** [comment]
> Tried pegging `pyannote-audio==3.0.1` in requirements.txt resulting in build errors:
> 
> > INFO: pip is looking at multiple versions of pyannote-audio to determine which version is compatible with other requirements. This could take a while.
> > 109.9 ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.16.0 (from pyannote-audio) (from versions: none)
> > 109.9 ERROR: No matching distribution found for onnxruntime-gpu>=1.16.0
> 
> Any ideas @mochan-a ?

Not sure what is going on.

I believe the author has removed `onnxruntime-gpu` requirement in a slightly newer version but before the `speechbrain` was added. I'll see if I can update all the requirements for my package to find a good version.

**Comment by sbc** [comment]
> Between @sbc, you should remain on `pyannote-audio==3.1.1` as  you can install `speechbrain` via `pip install git+https://github.com/speechbrain/speechbrain.git@develop` command. See, SpeechBrain's ECAPA-TDNN embeddings on Voxceleb via [HuggingFace](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb) for details.

@cataluna84 I tried installing the develop branch from github like you mention but it didn't work either. Please see the linked issue, which is brand new and points to the current version. Hopefully it gets resolved quickly if we need to stay on 3.1.1, or @mochan-a can find a working combination of dependencies.

**Comment by sbc** [comment]
For anyone following, I've confirmed that adding this to requirements.txt in place of the existing pyannote-audio does work:

git+https://github.com/Adel-Moumen/pyannote-audio.git@develop

**Comment by sbc** [comment]
I've added a working pyannote dependency to the requirements as a temporary fix. Let's keep an eye on the [tracking issue](https://github.com/pyannote/pyannote-audio/pull/1659) and update back to an official release as soon as the fix is accepted.

The PR is ready to merge and it fixes all outstanding reproduced issues.
 @cataluna84 @mochan-a

**Comment by cataluna84** [comment]
Great job @sbc! 🎯

Giving this PR some time to brew and to iron out some issues if they exist.

Will merge this in a day.

**Pull request merged**
