### PR TITLE
STT refactor

### PR DESCRIPTION
**Pull request by sbc**
This is a small refactor of the STT pipeline code to make it a bit easier to work with:

- **Move deployment related files to deploy dir**
- **Move api keys to env**
- **Move Drive related modules to folder**
- **Reorganize utils**

NOTE: The one is based on the FixSTT PR, so be sure to merge that first. Not sure if this will need to be resubmitted after because it includes some of those commits, or if gh will figure it all out.

### CODE REVIEW

**Comment by cataluna84** [comment]
Merged the FixSTT PR. I will merge this one in the next 12 hours.

@sbc Maybe, we need to update the documentation for moving API keys to env

**Comment by sbc** [comment]
> Maybe, we need to update the documentation for moving API keys to env

Done see latest commit

**Comment by cataluna84** [comment]
The recent ReadMe modifications have introduced some conflicts. I will resolve them and merge the branch soon.

**Comment by sbc** [comment]
@cataluna84 It looks like part of this commit was reverted, in particular I moved the Google stuff from the STT readme to it's own file.

See https://github.com/TWIML/TWIML-RAG/commit/cc3a0f630099ecdc04ad7774898e5879ee2f38cb

**Comment by cataluna84** [comment]
There was a conflict that I needed to resolve. In trying to fix that, the changes were rolled back. 

Can you fix this after making a new branch or in the same 'STT refactor' branch? I can revert the changes here @sbc

**Pull request merged**
